### ISSUE TITLE
nginx Container Open (13: Permission Denied)

### ISSUE THREAD

**Issue by midnightconman** [dockerfile/nginx#20]
I am trying to setup a private docker registry and I am getting this error from my nginx docker container:

2015/07/01 19:40:29 [crit] 6#0: *17 open() "/var/cache/nginx/client_temp/0000000001" failed (13: Permission denied)

I have verified that /var/cache/nginx/client_temp is writeable by nginx user. I have also added this to my dockerfile:

RUN chown +R nginx /var/cache/nginx

To make sure that nginx user has recursive permissions to this folder. Any ideas of what I can try next?

**Comment by hankerepo** [comment]
try setting selinux to permissive

**Comment by djcerdas** [comment]
It worked for me as a workaround, but no sure which should be the right SELinux context to used?

**Comment by djcerdas** [comment]
Hi, in /var/log/audit/audit.log you can see the error, and know which is the context, later on with semanage, you can configure the right context, that in my case was container_t.

**Comment by midnightconman** [comment]
This issue is stale, closing. :smile:
