### ISSUE TITLE
/var/lib/nginx/ Permission Denied

### ISSUE THREAD

**Issue by johnjelinek** [dockerfile/nginx#4]
I am seeing a lot of these permissions errors with proxied sites. Can you add permissions to `/var/lib/nginx/` as seen here: http://nishal-tech.blogspot.com/2013/06/nginx-13-permission-denied-while.html otherwise, I have to turn buffering off in my `site.conf`.

```
2014/05/14 17:50:52 [crit] 7#0: *111 open() "/var/lib/nginx/proxy/4/00/0000000004" failed (13: Permission denied) while reading upstream, client: 10.9.4.52, server: , request: "GET /assets/application.css?body=1 HTTP/1.1", upstream: "http://172.17.0.4:3000/assets/application.css?body=1", host: "kandan:8080", referrer: "http://kandan:8080/users/sign_in"
2014/05/14 17:50:52 [crit] 7#0: *44 open() "/var/lib/nginx/proxy/5/00/0000000005" failed (13: Permission denied) while reading upstream, client: 10.9.4.52, server: , request: "GET /assets/jquery.js?body=1 HTTP/1.1", upstream: "http://172.17.0.4:3000/assets/jquery.js?body=1", host: "kandan:8080", referrer: "http://kandan:8080/users/sign_in"
2014/05/14 17:50:53 [crit] 7#0: *47 open() "/var/lib/nginx/proxy/6/00/0000000006" failed (13: Permission denied) while reading upstream, client: 10.9.4.52, server: , request: "GET /assets/backbone/plugins/emoticons.js?body=1 HTTP/1.1", upstream: "http://172.17.0.4:3000/assets/backbone/plugins/emoticons.js?body=1", host: "kandan:8080", referrer: "http://kandan:8080/users/sign_in"
2014/05/14 17:50:56 [crit] 7#0: *51 open() "/var/lib/nginx/proxy/7/00/0000000007" failed (13: Permission denied) while reading upstream, client: 10.9.4.52, server: , request: "GET /assets/application.css?body=1 HTTP/1.1", upstream: "http://172.17.0.4:3000/assets/application.css?body=1", host: "kandan:8080", referrer: "http://kandan:8080/users/sign_in"
2014/05/14 17:50:56 [crit] 6#0: *259 open() "/var/lib/nginx/proxy/8/00/0000000008" failed (13: Permission denied) while reading upstream, client: 10.9.4.52, server: , request: "GET /assets/application.css?body=1 HTTP/1.1", upstream: "http://172.17.0.4:3000/assets/application.css?body=1", host: "kandan:8080", referrer: "http://kandan:8080/users/sign_in"
2014/05/14 17:50:56 [crit] 6#0: *260 open() "/var/lib/nginx/proxy/9/00/0000000009" failed (13: Permission denied) while reading upstream, client: 10.9.4.52, server: , request: "GET /assets/jquery.js?body=1 HTTP/1.1", upstream: "http://172.17.0.4:3000/assets/jquery.js?body=1", host: "kandan:8080", referrer: "http://kandan:8080/users/sign_in"
2014/05/14 17:50:57 [crit] 6#0: *275 open() "/var/lib/nginx/proxy/0/01/0000000010" failed (13: Permission denied) while reading upstream, client: 10.9.4.52, server: , request: "GET /assets/backbone/plugins/emoticons.js?body=1 HTTP/1.1", upstream: "http://172.17.0.4:3000/assets/backbone/plugins/emoticons.js?body=1", host: "kandan:8080", referrer: "http://kandan:8080/users/sign_in"
2014/05/14 17:51:09 [crit] 6#0: *331 open() "/var/lib/nginx/proxy/1/01/0000000011" failed (13: Permission denied) while reading upstream, client: 10.9.4.52, server: , request: "GET /assets/application.css?body=1 HTTP/1.1", upstream: "http://172.17.0.4:3000/assets/application.css?body=1", host: "kandan:8080", referrer: "http://kandan:8080/users/sign_in"
2014/05/14 17:51:10 [crit] 6#0: *257 open() "/var/lib/nginx/proxy/2/01/0000000012" failed (13: Permission denied) while reading upstream, client: 10.9.4.52, server: , request: "GET /assets/jquery.js?body=1 HTTP/1.1", upstream: "http://172.17.0.4:3000/assets/jquery.js?body=1", host: "kandan:8080", referrer: "http://kandan:8080/users/sign_in"
2014/05/14 17:51:11 [crit] 6#0: *258 open() "/var/lib/nginx/proxy/3/01/0000000013" failed (13: Permission denied) while reading upstream, client: 10.9.4.52, server: , request: "GET /assets/backbone/plugins/emoticons.js?body=1 HTTP/1.1", upstream: "http://172.17.0.4:3000/assets/backbone/plugins/emoticons.js?body=1", host: "kandan:8080", referrer: "http://kandan:8080/users/sign_in"
```

**Comment by mascor** [comment]
I'm having the same problem:

10916#0: *1 open() "/var/lib/nginx/tmp/fastcgi/1/00/0000000001" failed (13: Permission denied) while reading upstream...
The server is based on Centos 7 64 bit with Ajenti V.
I'm using Wordpress and this error run when I try to execute a script: GET /wp-admin/load-scripts.php which calls a lot of javascripts. I started to have this problem after an update of the system I verified the file /etc/php-fpm.conf and I have for every website this configuration:

[xxxxxxxxx-php-fcgi-0]
user = www-data
group = www-data

listen = /var/run/ajenti-v-php-fcgi-xxxxxxxxx-php-fcgi-0.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660

pm = dynamic
pm.max_children = 5
pm.start_servers = 1
pm.min_spare_servers = 1
pm.max_spare_servers = 5

php_admin_value[open_basedir] = none
I also verified the permission of /var/lib/nginx/tmp

drwxrwx---  2 www-data www-data 4096 10 mag 14.21 client_body
drwxrwx--- 12 www-data www-data 4096 21 mar 10.00 fastcgi
drwxrwx---  2 www-data www-data 4096  5 mar 16.50 proxy
drwxrwx---  2 www-data www-data 4096  5 mar 16.50 scgi
drwxrwx---  2 www-data www-data 4096  5 mar 16.50 uwsgi

And I also added nginx to www-data group, but the problem is the same

**Comment by mascor** [comment]
SORRY...
SOLVED: chown -R www-data:www-data /var/lib/nginx

**Comment by mascor** [comment]
SOLVED: 
chown -R www-data:www-data /var/lib/nginx

**Comment by adrian7** [comment]
I am having the same issue, although I did chown -R www-data:www-data /var/lib/nginx .
Also seems to trigger only when uploading files larger then 4kb.

**Comment by carlalexander** [comment]
I'm also running into the same issue as @adrian7 (works for files under 4kb). It's not consistent though. It only happens when I switch the user id of `www-data` to workaround a [known boot2docker issue](https://github.com/boot2docker/boot2docker/issues/581).

**Comment by adrian7** [comment]
@carlalexander After some reading it's not an issue with docker, but with nginx and maybe because in my case it's running under supervisord. I just added `client_body_temp_path /var/www/tmp 1 2;` in `sites-available/default.conf` and solved the issue. 

More on this here https://wincent.com/wiki/Fixing_nginx_client_body_temp_permission_denied_errors

**Comment by adrian7** [comment]
BTW /var/www/ is a shared volume

**Comment by carlalexander** [comment]
Thanks @adrian7, will look at that!

**Comment by carlalexander** [comment]
I used `/tmp` instead of `/var/www/tmp`. Worked like a charm. Thanks!

**Comment by Ocramius** [comment]
Note: if you don't deal with uploaded files, you can just set a higher `client_body_buffer_size`.

Setting a high `client_body_buffer_size` also reduces file I/O, which is kinda good if you don't have a fast filesystem (virtual environments): 

To sum it up, you need to just customize this bit of your config:

```
http {
    # ...

    client_body_temp_path /tmp 1 2;
    client_body_buffer_size 256k;
    client_body_in_file_only off;

    # ...
}
```

**Comment by dcwangmit01** [comment]
In some versions of nginx docker images the nginx runs as user "nginx" instead of "www-data".  This is why the `chown -R www-data:www-data /var/lib/nginx` worked for some people and not others.  Changing the location to /tmp works because /tmp is writable for all users.  The buffer_size fix might only work if you have small files.

**Comment by sacdallago** [comment]
For anyone landing here having this problem in uwsgi or similar: if you use an include like `include /etc/nginx/uwsgi_params;`, you need to change the temp file location for that specific handler, i.e.:


```
# Override temp file locations
client_body_temp_path /var/lib/nginx-tmp/client_body;
proxy_temp_path /var/lib/nginx-tmp/proxy;
fastcgi_temp_path /var/lib/nginx-tmp/fastcgi 1 2;
uwsgi_temp_path /var/lib/nginx-tmp/uwsgi;
scgi_temp_path /var/lib/nginx-tmp/scgi;
```

**Comment by kunal097** [comment]
@johnjelinek is your issue resolved?
I'm getting exactly same issue.
Please help!!

**Comment by kunal097** [comment]
![error](https://user-images.githubusercontent.com/23140769/46021393-38161e80-c0fe-11e8-9423-df1acef2de6a.png)

**Comment by 6a** [comment]
> For anyone landing here having this problem in uwsgi or similar: if you use an include like `include /etc/nginx/uwsgi_params;`, you need to change the temp file location for that specific handler, i.e.:
> 
> ```
> # Override temp file locations
> client_body_temp_path /var/lib/nginx-tmp/client_body;
> proxy_temp_path /var/lib/nginx-tmp/proxy;
> fastcgi_temp_path /var/lib/nginx-tmp/fastcgi 1 2;
> uwsgi_temp_path /var/lib/nginx-tmp/uwsgi;
> scgi_temp_path /var/lib/nginx-tmp/scgi;
> ```

This fix worked! Thank you.

**Comment by SunLn** [comment]
I am in macOs Mojave. Solved by 

```
ps aux | grep "nginx: worker process"
sudo chown -R your_current_nginx_user:admin /usr/local/var/run/nginx/proxy_temp/
sudo nginx -s reload
```

**Comment by huzineczerik** [comment]
> SOLVED:
> chown -R www-data:www-data /var/lib/nginx

The heroes live among us!

**Comment by geeksrus** [comment]
> Note: if you don't deal with uploaded files, you can just set a higher `client_body_buffer_size`.
> 
> Setting a high `client_body_buffer_size` also reduces file I/O, which is kinda good if you don't have a fast filesystem (virtual environments):
> 
> To sum it up, you need to just customize this bit of your config:
> 
> ```
> http {
>     # ...
> 
>     client_body_temp_path /tmp 1 2;
>     client_body_buffer_size 256k;
>     client_body_in_file_only off;
> 
>     # ...
> }
> ```

this worked for me, thanks!

client_body_temp_path /tmp 1 2;

**Comment by jdmarshall** [comment]
The 'closed' solution doesn't work if you mount /var/lib/nginx/tmp as a tmpfs, since you can't change the user for a mount.
